In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5,6,7,8,9,0])
b = np.zeros([2,3],int)
c = np.ones(9)

In [3]:
b

array([[0, 0, 0],
       [0, 0, 0]])

In [4]:
c

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
a.reshape(2,5)

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [6]:
a.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [7]:
T = a.reshape(2,5).transpose()
T

array([[1, 6],
       [2, 7],
       [3, 8],
       [4, 9],
       [5, 0]])

In [8]:
d2 = np.arange(-25,25,5).reshape(2,5)
d2

array([[-25, -20, -15, -10,  -5],
       [  0,   5,  10,  15,  20]])

In [9]:
avg = np.average(d2)
avg

np.float64(-2.5)

In [10]:
below_zero = []
for i in range(len(d2)):
    for j in range(len(d2[i])):
        if d2[i][j] < 0:
            below_zero.append(d2[i][j])
print(f"Elements Below 0 are : {below_zero}")

Elements Below 0 are : [np.int64(-25), np.int64(-20), np.int64(-15), np.int64(-10), np.int64(-5)]


In [11]:
print(f"Total No. of Element : {d2.size}")

Total No. of Element : 10
